
#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_house?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  mvc:
    format:
      date: yyyy-MM-dd
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

#整合mybatis
mybatis:
  #加载实体类
  type-aliases-package: com.example.groupproject.entity
  #映射文件
  mapper-locations: mapper/*Mapper.xml
  #输出日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8088




